### ISSUE TITLE
"None" is returned for some scans 

### ISSUE THREAD

**Issue by tophertimzen** [0xdade/nweb#1]
We scan only specific ports with masscan so when it's not open we never see the "Nmap scan report for" line that is currently split on.

We wind up getting None for the get_ip() call.

"None" should not appear in search results.

**Comment by 0xdade** [comment]
Example scan output so we can try to reproduce to confirm fix.

# Nmap 7.40 scan initiated Tue Jun  5 23:37:13 2018 as: nmap -oA data/nweb.ah7qm5d4ff -A -open -p 3000 10.x.x.x
Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
# Nmap done at Tue Jun  5 23:37:14 2018 -- 1 IP address (1 host up) scanned in 0.56 seconds
